apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secret
  namespace: weather-mlops
  labels:
    app.kubernetes.io/name: weather-api
    app.kubernetes.io/part-of: weather-mlops
type: Opaque
stringData:
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "open-meteo"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
